language: node_js
node_js: node
services: mongodb
env: MONGODB_URI=mongodb://localhost:27017/notes
deploy:
  provider: heroku
  api_key:
    secure: er+by9FotSpmZLIVZblZO1MrGTQw5guJEfv/A6I74T5hRvJi45amUXxgZJnb4QCGvh39EJ3HqYDsNmZQz8mF4GVGaqhP1V3n38duMmihYg7MxDBxUIusbMhb54Wct6StRAhTVTVlv2YSuHtQ63ZbwwuBpyHZIMwOORT7Z1wTl6NSpvBhGwvioWbh70MMnryT8EO7V5Z1IeSZH22bUuT0kyByYnOJwYWaW7akjasDh1oAQppjVYJ1pMg0DDJSsTuY5Qd+nKRI9J7aPINhX8Kxm4SV6vliQ5+SwcNV9w+eIia9vWBjThj72m5GBi+cg6pvc3yGrpeAQn7PyW9L4i3W5qKP2fXT1fNl+EWrJzxo3zcs0BFbukSB822HMH3Z7xzsQezyanoVyfL0L8bv/qjS74pgym1nyoYykIoPpWJPS+2yQZw3tNSAOUrpphCEnsEMY9P1LWIJgVnSKu2aa0LkHXDKRfbUtLuhG93pBlPDpItf93WneomzD11hi466o+E2M92+BJj0B8z8/O0cunsjJL6omcXlN1utSHczJ/umL2yjumEGMkrGDA8cBFOWp/dkY8FelS525MEvqn1l56+rbCskePiChMBe6BiLTpdEdCYi2xhM/NrCTaz4JLhS+qOH9uKP+wQs6jseg73xHDxaGheMm477Jezj/4QVge1fqXA=
  app: notes-server-ct19
